### ISSUE TITLE
snactor installation not working

### ISSUE THREAD

**Issue by artmello** [leapp-to/snactor#9]
After installing snactor
```
$ pip install --user .
Processing /home/amello/projects/leapp/github.com/snactor
Installing collected packages: snactor
  Running setup.py install for snactor ... done
Successfully installed snactor-0.1
```

loading module is not working

```
$ python
Python 2.7.13 (default, Jun 26 2017, 10:20:05) 
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from snactor.loader import load
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amello/.local/lib/python2.7/site-packages/snactor/loader.py", line 4, in <module>
    from snactor.executors.default import ExecutorDefinition
ImportError: No module named executors.default
>>> 
$ ls /home/amello/.local/lib/python2.7/site-packages/snactor/
definition.py   __init__.py   loader.py   registry.py
definition.pyc  __init__.pyc  loader.pyc  registry.pyc

```

**Comment by vinzenz** [comment]
Should be fixed by #10
